{% set name = "email_validator" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JoshData/python-email-validator/archive/v{{ version }}.tar.gz
  sha256: 4970d17437d3bb1a5318f1fcd22b1117858d9d6e12657501279e862d98339a1d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

  entry_points:
    - email_validator = email_validator:main

requirements:
  host:
    - python
    - pip

  run:
    - python
    - idna >=2.0.0
    - dnspython >=1.15.0

test:
  imports:
    - email_validator

  commands:
    - email_validator --help

about:
  home: https://github.com/JoshData/python-email-validator
  license_file: LICENSE
  license: CC0-1.0
  license_family: CC
  summary: A robust email syntax and deliverability validation library for Python 2.x/3.x.
  dev_url: https://github.com/JoshData/python-email-validator
  doc_url: https://github.com/JoshData/python-email-validator

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
