travis:
  secure:
    BINSTAR_TOKEN: Hk+/usdMXZ7bQXuDaFUAp9A9f080dgulwRFeoynT7lKQvPfTXTb/dJ04DyhM71dxfNvDLrcOQSN7LXtc4DzI/xo78XnhKx7bt5SjqohywAdy1prbofO1CZ9eFukONcncoUXGJ5/OO37viM/HITmxWsUISgrjQSGxIJpv/Kos1faOrYimtE9gZBP/T+hD5RFZrS830Ox1BFkG1OJ8ysMFXVQ6/qSkmWkJRKmJHPhYfnTSdaJI6LQanjPZyNW10/PfEHvRYWFGZPFmIjFHuDR9rnEzLUtAyxNPkeERBdWWhG8JkVaUEf35MU4Cud7xpDHpYvxENsTKs3oM/nRPGpY8EJGnuecpC2KAZdm8ycpxkTGLEQdRDmLlekF/I3kVBsSbOHi7d0TO8uTfiGPKdvy6bxyxomVG52siyNg9hOaZSPAm1R91evC5tpZjvnirFstH62q77G8DNl45xKwsX5efrxFDqqPlf7WzSZj0KLf088NLHggyg53FSVe1RQppfAdP45alPBs76+O5kgjxHwaotjnAS1kvFgQv4stigH07HuIbVSvG1As3rRu90FLwRxalTXq8gnsxnOg1VD6ez6aGAgSL5oehmrathlP9S2W+WGi1+8znvYZhKIye1rqocBuMrm7TIezBD8nLt+1sWhO3LlyyvRWA2dYvDV1zD5bumrs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
