travis:
  secure:
    BINSTAR_TOKEN: dhsY4792kvjZ6Y6Ph76O6HEOO5oe+filCNzJ7dyE5SGUDh3DrLYpLfVbUDiE4Mm8g8sutiv2bkz9cfVZJslivv0FwcBO1HP77D4Ku/Kz/yV5Qzf2eVFY80psCmO7sr1EqwiwspURwhuy88VXc5/j3g30Dq79Oi7/y84kR9OQJb1vSjitS/D9/XFM4FRq8ouO4cLKSkCte9DT727eJJW/BNep47g0s4/JAidjRHPml4a64DbK+DToP/4OF/nHVVb2eJ7TZJZ8Xz+ufN40k0c7ttROukI+WSeHtKR3uBG1uO+Ateg9QdlM6d7gAPUCNHlce5T/ElYDRc4BA2TVQEJjHBcEH6zfn+g69kOyP3//7SX5plkW9NPpka1iqwG1JxhP+etWwKC0+qkAEdjs6dsQE+PMSMYKJEWD9vxIdHY7m418UJhIp5BJM7wSAPQk8/L2kNIJrc2gLfXFvyjKQCEuaXyg9qwK5h6UYyA0R07UF81hUglnfFJjmPSEE/K6JFyqO3Tg7zY29OUGfzyD32J2qFyZRv38/z0H/weNpMEcSAtBJ3vwU2v9cuyZpJCnWmGZd8eEIimDIq1ZAaC6dAYgCHIjAoo96uTQiDWiJLiPC/IKGTqfDf3XNnJnsa9diH3OhYIXLlsWMXeph3FvWzcDmC5wWJGMAKAztxRRfhM00z0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
